In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]

np.int64(1)

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [ ]:
a[:3]

array([10,  2,  3])

In [ ]:
b = a[3:]
b

array([4, 5, 6])

In [ ]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1, 3]

np.int64(8)

In [ ]:
a.ndim

2

In [ ]:
a.shape
len(a.shape) == a.ndim

True

In [ ]:
a.size
import math
a.size == math.prod(a.shape)

True

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size
import math
a.size == math.prod(a.shape)

True

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])